import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BlurBackground from "@/components/BlurBackground";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative min-h-screen">
        <Navbar />
        <Sidebar />
        <BlurBackground />
        {children}
      </body>
    </html>
  );
}
